# SPDX-License-Identifier: Apache-2.0

'''bflb_test_command.py
West command for controlling a test rig.
'''

import time
import os
import subprocess
import shutil
import sys
import yaml
from west.commands import ExtensionCommandError
from west.commands import WestCommand

class BflbTestCommand(WestCommand):
    '''Class for the bflb-test command'''

    def __init__(self):
        super().__init__(
            'bflb-test',
            'Control a test rig for BouffaloLab testing',
            'Manage a test rig and test results. See the README for an example.'
        )

    def do_add_parser(self, parser_adder):
        parser = parser_adder.add_parser(
            self.name, help=self.help, description=self.description
        )

        subparsers = parser.add_subparsers(dest='subcmd')

        parser_init = subparsers.add_parser(
            'init', help='Initialize a new test rig'
        )
        parser_init.add_argument('name', help='name of the test rig to initialize')

        parser_set = subparsers.add_parser(
            'set', help='Assign a serial console to a board into the hardware map'
        )
        parser_set.add_argument('serial', help='path to the serial console (i.e. /dev/ttyACM0)')
        parser_set.add_argument('board', help='board name to add (i.e. ai_m61_32s_kit)')

        parser_del = subparsers.add_parser(
            'del', help='Delete a board from the test rig'
        )
        parser_del.add_argument('serial', help='board name to delete (i.e. ai_m61_32s_kit)')

        parser_list = subparsers.add_parser(
            'list', help='List the boards from the test rig'
        )

        parser_run = subparsers.add_parser(
            'run', help='Run twister with default arguments and extra; given arguments'
        )
        parser_run.add_argument('extra', help='extra args i.e. -- -T samples/hello_world', nargs='*')

        parser_html = subparsers.add_parser(
            'html', help='Generate HTML report of all the tests currently stored'
        )

        parser_push = subparsers.add_parser(
            'push', help='Push the current results using git so they can be visible online'
        )

        return parser

    def error(self, msg):
        print(f'error: {msg}')
        sys.exit(1)

    def run_cmd(self, *args):
        print(' '.join(args))
        return subprocess.run(args)

    def git(self, *args):
        self.run_cmd('git', '-C', self.repo_path('.'), *args).check_returncode()

    def rig_name(self):
        name = self.config.get('bflb-test.rig')
        if name is None:
            self.error('Call "init" first to set the rig name')
        return name

    def repo_path(self, path):
        return os.path.realpath(os.path.dirname(__file__) + '/../' + path)

    def hwmap_path(self):
        return self.repo_path('rigs/' + self.rig_name() + '.hwmap.yml')

    def hwmap_yaml(self):
        with open(self.hwmap_path(), 'a+') as f:
            pass
        with open(self.hwmap_path(), 'r') as f:
            return yaml.safe_load(f)

    def hwmap_list(self, hwmap):
        for row in hwmap:
            status = 'ok' if os.path.exists(row['serial']) else 'off'
            print(f'  {status:3} {row["id"]} {row["platform"]}')

    def hwmap_del(self, hwmap, id):
        return [x for x in hwmap if x['id'] != id]

    def hwmap_save(self, hwmap):
        with open(self.hwmap_path(), 'w') as f:
            yaml.dump(hwmap, f, default_flow_style=False)

    def subcmd_init(self, args):
        self.config.set('bflb-test.rig', args.name)
        print(f'Test rig name set to "{args.name}" in {self.config._local_path}')

    def subcmd_del(self, args):
        hwmap = self.hwmap_yaml() or []
        hwmap = self.hwmap_del(hwmap, args.serial)
        self.hwmap_save(hwmap)
        self.hwmap_list(hwmap)

    def subcmd_set(self, args):
        if not os.path.exists(args.serial):
            self.error(f'{args.serial} serial console not found')
        hwmap = self.hwmap_yaml() or []
        hwmap = self.hwmap_del(hwmap, args.serial)
        hwmap.extend([{
            'connected': True,
            'flash_before': True,
            'id': args.serial,
            'notes': 'generated by "west bflb-test" command',
            'platform': args.board,
            'product': args.board,
            'runner': 'bflb_mcu_tool',
            'runner_params': [f'--dev-id={args.serial}'],
            'serial': args.serial,
        }])
        self.hwmap_save(hwmap)
        self.hwmap_list(hwmap)

    def subcmd_list(self, args):
        hwmap = self.hwmap_yaml() or []
        self.hwmap_list(hwmap)

    def subcmd_run(self, args):
        result = self.run_cmd(
            'west', 'twister', '--device-testing', '--hardware-map', self.hwmap_path(), *args.extra
        )

        if result.returncode != 0:
            self.error(f'command {result.args} failed with status {result.returncode}')

        dir = self.repo_path(f'results/{self.rig_name()}')
        filename = time.strftime('date_%Y_%m_%d_time_%H_%M_%s_utc.json')

        os.mkdir(dir)

        shutil.copyfile('twister-out/twister.json', dir + '/' + filename)

    def subcmd_push(self, args):
        self.git('add', '.')
        self.git('commit', '-m', f'publish results for {self.rig_name()}')
        self.git('pull', '--rebase')
        self.git('push', 'origin')

    def subcmd_html(self, args):
        print('html', args)

    def do_run(self, args, _):
        if args.subcmd is None:
            self.parser.print_help()
            sys.exit(1)
        subcmd = getattr(self, 'subcmd_' + args.subcmd)
        subcmd(args)
